/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("wikisearch.kotlin-application-conventions")
}

repositories {
    maven {
        url = uri("https://jitpack.io")
    }
    mavenCentral()
}


dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("com.londogard:smile-nlp-kt:1.1.0")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("wikisearch.app.AppKt")
}
