/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package wikisearch.app

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotEquals

class AppTest {
    @Test fun testLoadDocuments() {
        assertNotEquals(0, App.getDocs().size)
    }
}
